#!/bin/sh
if [ -d "$1" ]; then
  cd "$1"
  echo Enter into $1
  for file in *; do
    if [ -f "$file" ]; then
      # if file name starts with character n-
        if [[ $file == n-* ]]; then
            chmod a+x "./$file"
            echo changed permissions of "./$file"
        fi
    fi
  done
else
  echo "Directory does not exist."
fi

####### 1st part of the script #######
# multiline comment 
# This is an if statement in a shell script that checks if the variable "file" starts with a hyphen (-). The double square brackets are used to test conditions in shell scripts.

# The expression "$file == -*" checks whether the value of the variable "file" starts with a hyphen (-). The double equals sign (==) is used for string comparison.

# If the condition is true, i.e., if the value of the variable "file" starts with a hyphen (-), then the commands inside the if statement will be executed. If the condition is false, the commands inside the if statement will be skipped and the script will continue to the next statement.

# This check is often used to prevent potential problems when dealing with filenames or command line arguments that start with a hyphen (-), as they can be interpreted as options by command line utilities if not properly handled.

######### 2nd part of the script #########
# Add the export command to the mac's .bash_profile file
# vim ~/.zshrc

# Add /Users/asif/git-gh/misc/home_media_server_laravel to the PATH variable
# export PATH=$PATH:/Users/asif/git-gh/misc/home_media_server_laravel