name: CI - Notebull
on:
  push:
    branches: [ master ]

jobs:
  build:
    # runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v18.16.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'
      - name: Setup Java 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
