name: CI - Notebull
on:
  push:
    branches: [master]
# runs-on: [ubuntu-latest, macos-latest, windows-latest]

jobs:
  build:
    runs-on: [macos-latest]


    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v18.16.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'
      - uses: actions/checkout@v3
        name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build with Maven
        run: mvn -B package --file pom.xml
