name: CI - Notebull v4
on:
  push:
    branches: [main]
# runs-on: [ubuntu-latest, macos-latest, windows-latest]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'

      - name: set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      
      - name: Build with Maven
        run: |
          java --version
          node --version
          mvn -B package --file pom.xml
