# write basic workflow
name: CI - Notebull
on:
  push:
    branches: [ master ]

jobs:
  build:
    # run on mac, windows and linux ubuntu latest in array
    # runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js v18.16.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'
      name: setup Java 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'